version: '3'

services:
  web:
    build:
      context: ./dockerserver
      dockerfile: Dockerfile
    image: jkdky05/dockerbackend:latest  
    ports:
      - '8080:8080'

  client:
    build: 
      context: ./dockerfront
      dockerfile: Dockerfile
    image: jkdky05/dockerfrontend:latest
    ports:
      - '8500:3000'
    depends_on:
      - web
    command: npm start
